### PR TITLE
LRDOCS-6958 Improve the Messed Up Data Providers

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-6958

@rbohl I did my normal `git difftool master` thing with this PR; did a bunch of wordsmithing in a bunch of files, and then noticed all the image links were broken in the file I was in (using-data-providers-to-populate-form-options.md). So I fixed all the links. I continued, and Vim kept bringing up new files, and I fixed some links there too. Then I was brought to a file with the same name as all the broken links, and I realized it was in the `ja` folder. 

Now, I know this tended to happen after @jrhoun renamed `7.x` to `latest`, because in other PRs I moved a lot of files git had attempted to merge into the `ja` folder instead of into the `en` folder. So I'm assuming that happened, to you, you didn't notice, you committed the file into the `ja` folder, and then you sent it to me. But I can't be sure, because I don't know the content. In any case, I copied the file (using-the-rest-data-provider-to-populate-form-options.md) into the `en` folder where it belongs. So now there are probably two files with the same content and different names, and broken links everywhere. 

I'm sending this back to you in case you can make sense of it. I expect, however, that you may need to start by fixing your own branch and sending it back to me, which means I'll lose the wordsmithing I did. That's an acceptable loss to me; it may be easier for both of us to start over. 

- LRDOCS-6958 generally improving the overview article
- LRDOCS-6958 disambiguation: using data providers to populate form options > using the rest data provider to populate form options
- LRDOCS-6958 wordsmithing
- LRDOCS-6958 Wordsmithing and probably broke a lot of stuff.

### CODE REVIEW

**Comment by rbohl** [comment]
okay, i think i get it--and i think we can fix it :toolbox: :hammer_and_wrench: 

my fault for failing to recognize that one was somehow shuffled to `ja` :man_shrugging:

**Comment by rbohl** [comment]
oh wait, i see--you wordsmithed the article in `ja` but i worked on the renamed version in `en`, so they've diverged. this will take a little thinking.

Worse case scenario: I'll use my branch, delete the `ja` article, and manually redo your edits in the `en` file. I think that'd cover us, but whatever I come up with I'll test drive it in a local site build.

**Comment by sez11a** [comment]
Yeah; I did `git difftool master`, which is how I edit these PRs that contain changes in a bunch of files. That just brings up each file one by one for me to edit. I didn't realize there was one copy in `ja` and one copy in `en` until I'd already edited the first one git presented to me (which turned out to be the `ja` version, though I didn't take note of the path at the time). Oddly, there were changes in the `ja` file, as though it had been edited, which is why I didn't think anything was amiss until git started bringing up the other files one by one.

**Comment by rbohl** [comment]
Fortunately we had both wordmishted the same article, so deleting the other one and re-renaming was all that was nbeeded (my `rename.py` python script fixes up the links and renames automatically :man_dancing: ).

Superseded by https://github.com/sez11a/liferay-learn/pull/427

**Pull request closed without merging**
