### PR TITLE
LRDOCS-8710 Forms / Workflow Reorganization

### PR DESCRIPTION
**Pull request by jrhoun**
Hey @rbohl -

I wanted to run this reorg of forms / workflow by you. If it looks good enough, then I'll merge it and begin reviewing and de-conflicting a lot of the other subsequent pulls I have in my queue related to F&W.

## Forms (Before)

image

## Forms (After)

image

## Workflow (Before)

image

## Workflow (After)

image

CC @jamesAgarcia

### CODE REVIEW

**Comment by rbohl** [comment]
I like it, certainly far better than the existing structure. Couple points:

1. Forms (After): _APIs_ appears in the left nav but not any of the cards. To me APIs should go inside the Developer Guide section.
2. [basically same as 1] Workflow > _APIs_ appears in the body as a card and in the left nav. I recommend it as a subsection under Developer Guide.
3. I need to port or else farm out Kaleo Forms and DDL docs. I think these slipped through the cracks :disappointed:

**Comment by rbohl** [comment]
You know, in light of the currently unoptimized search functionality on our site, fragmenting sections like this will make it harder to see at a glance what's contained in a section, so could actually reduce browsability. Just a thought.

**Comment by jrhoun** [comment]
Hey @rbohl 
> Forms (After): APIs appears in the left nav but not any of the cards. To me APIs should go inside the Developer Guide section.
[basically same as 1] Workflow (After): APIs appears in the body as a card and in the left nav. I recommend it as a subsection under Developer Guide.

Yeah i agree with these points. I'll update that.

> You know, in light of the currently unoptimized search functionality on our site, fragmenting sections like this will make it harder to see at a glance what's contained in a section, so could actually reduce browsability.

_Sigh_. Yeah search and the lacking of real redirects is making me lose sleep. My hope (separate from meaningfully improving search in the future) is that although it fragments the articles, it fragments them in meaningful ways and when those fragments/sections aren't clearly as meaningful that the cards w/ the example contents in them would help illuminate the kind of content that users can expect to find.

**Comment by jrhoun** [comment]
Ok going to push forward w/ the changes to move the apis sections under Dev Guide. Thanks!

**Pull request closed without merging**
