### PR TITLE
LRDOCS-9736 Upgrading Search for 7.4 Wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-9736

@rbohl When converting to MyST syntax, remember the links in admonitions also have to be converted to Markdown syntax. I'm sending this back because also when we convert to MyST, we don't use underscores in the Markdown file names. They become dashes instead. I almost renamed them myself, but then I thought that because links to these files appear in the navigation, I better let you do it because you know the navigation better. 

- LRDOCS-9736, * Copy the Upgrading Search for Liferay 7.3 article * Begin editing and making notes for 7.4 scenario * Navigation and other edits and comments
- LRDOCS-9736 after SME consultation, began making a single standalone article to encompass the upgrade paths
- LRDOCS-9736 shift the focus form 7.3 to 7.4 or neutral
- LRDOCS-9736 Replace 7.3 references with "7.3+" or "Liferay 7.3 and 7.4"
- LRDOCS-9736 remove the old "upgrading search" articles
- LRDOCS-9736 Make requested SME edits and navigation fixes
- LRDOCS-9736 Edit
- LRDOCS-9736 Review edits
- LRDOCS-9736 Rename + edits
- LRDOCS-9736 tidy up navigation and minor edits
- LRDOCS-9736 usage of the groovy script for manual import: tuning indexes > tuning database tables
- LRDOCS-9736 update the version references and screenshots
- LRDOCS-9736 update refs to .rst with .md
- LRDOCS-9736 rename *.rst > *.md
- LRDOCS-9736 update all nav pages to MYST syntax; remove the User Guide section, it's obsolete
- LRDOCS-9736 cleanup
- LRDOCS-9736 these README files are obsolete
- LRDOCS-9736 Wordsmithing.

### CODE REVIEW

**Comment by rbohl** [comment]
Merged Locally

**Comment by rbohl** [comment]
@sez11a do we need to do this for `ja` and `en`?

**Comment by sez11a** [comment]
Yes; I missed that. When we reorganize, we do ja too.

**Comment by rbohl** [comment]
Resent here: https://github.com/sez11a/liferay-learn/pull/664

**Pull request closed without merging**
