### PR TITLE
LRDOCS-9390 Settings and Accessing Configurations

### PR DESCRIPTION
**Pull request by mtokudome**
https://issues.liferay.com/browse/LRDOCS-9390

Hi @rbohl here's my initial draft on this first article. Would love to get your feedback on it before I send it to KM review. Thanks!

### CODE REVIEW

**Comment by rbohl** [comment]
Hi Makoto, looks like this is merge conflicted.

**Comment by mtokudome** [comment]
@rbohl Okay, let's try again

**Comment by rbohl** [comment]
Merged Locally.

**Comment by rbohl** [comment]
superseded by https://github.com/mtokudome/liferay-learn/pull/10

**Pull request closed without merging**
