### PR TITLE
workflow 7.x | using condition evaluators | LRDOCS-9253

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-9253
@rafaprax this is the condition evaluators article. can you review it for accuracy and completeness (is there anything else our users should know about condition evaluators)?

### CODE REVIEW

**Comment by rbohl** [comment]
@rafaprax, we use an include statement to dynamically ingest and display source code snippets, so unfortunately yuou can't see the code snippets I included by looking at the source markdown. If you'd like to see the rendered article including the code snippets, uncompress this ZIP file, which is a miniature build of the Liferay Learn site: [output.zip](https://github.com/rbohl/liferay-learn/files/6970058/output.zip)

Open `output/dxp/latest/en/process-automation/workflow/developer-guide/creating-a-condition-evaluator.html`

**Comment by rafaprax** [comment]
Hey @rbohl , everything is ok. Thank you and sorry for the delay.

**Comment by rbohl** [comment]
Thanks, and no problem @rafaprax !

**Comment by rbohl** [comment]
Forwarded: https://github.com/sez11a/liferay-learn/pull/564

**Pull request closed without merging**
