### PR TITLE
Solr 8 docs for 7.1 & 7.2

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LRDOCS-9429

Hey Russ,

Please review my changes.

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
Skip sending it to Rich if possible to have it published sooner.

**Comment by lipusz** [comment]
We could add an extra section with basic instructions from upgrading from Solr 7 to 8:
1. refer to https://solr.apache.org/guide/8_8/major-changes-in-solr-8.html#major-changes-in-solr-8
2. indicate to uninstall and delete the Solr 7 connector LPKGs from the installation
3. When using config files, renaming them from `solr7` to `solr8` should be enough.

**Comment by lipusz** [comment]
Hey Russ, @rbohl 

Do you have any news on this?

Thanks,
Tibor

**Comment by rbohl** [comment]
No news, but thanks for the bump--I can likely begin looking at it Monday--I assume, since you sent me a PR for this, it is more important than CCR for 7.1?

**Comment by lipusz** [comment]
Yes, because this is already released, CCR and ES7 are not. :-)

**Comment by rbohl** [comment]
Merged locally.

**Comment by rbohl** [comment]
Forwarded: https://github.com/jrhoun/liferay-learn/pull/1059

**Pull request closed without merging**
